### ISSUE TITLE
Erasing Runes

### ISSUE THREAD

**Issue by Raclex** [stirante/RuneChanger#1]
v1.3 always used the same slot for these runepages, which I thought was perfect. Something changed in v1.4 that now causes it to inject the runes in the last page, and bump the top runes off, causing my rune pages to disappear. I had to dodge a game because my personal preset runes were gone that I needed. I don't like this new change.

**Comment by stirante** [comment]
Thank you for your feedback.

I had to change the way the runes are injected, because there were some issues, when you tried to edit the page you injected.
I'll try to adjust new way of injecting to be more like in version 1.3 or add an option to change the behavior to the old one.

I'll comment here when new version will be released.

**Comment by stirante** [comment]
@Raclex I updated rune injecting.
https://github.com/stirante/RuneChanger/releases/tag/1.5

Let me know if it's working as it should. Until then I'm marking this as closed.
