### ISSUE TITLE
[Feature request] Automatic role typing and sending

### ISSUE THREAD

**Issue by DanVerseDev** [stirante/RuneChanger#31]
The idea would be that you can select the lane from a custom list (I use adc, supp, top, mid & jg but the app only shows 3 lanes) and when it's connected automatically send the role.

It would be useful for people with slow PCs, but I don't know if it's allowed by Rito to automatically typing and sending text.

**Comment by stirante** [comment]
The decision to put only three lanes was because I have no idea where I could possibly put 5 buttons in client. Other than that, this is something we could add in the future, but maybe with like 1 second delay.

Thanks for suggestions! Be sure to tell us if you have more of them. Also we have a (very small) discord dedicated to RuneChanger, so feel free to check it out. Invite is in README.

**Comment by DanVerseDev** [comment]
Maybe in the program gui to show the lane you want.

The delay of one second also would be good since not everyone connects at the same time.

I will join the discord, anything i could suggest/contribute i would tell, like completing the spanish translation for this and future features :)
PS: Sorry for my bad english

**Comment by stirante** [comment]
This has been implemented in newest version in experimental channel.
