### ISSUE TITLE
[Request] LoLTheory.gg rune pages

### ISSUE THREAD

**Issue by agaertner** [stirante/RuneChanger#65]
LoLTheory.gg is a hidden gem. Its uniqueness stems from creating rune pages and calculating win rates per item and buy order with the usage of artifical intelligence.
It is for this reason my goto site, not only because it loads waaay faster than u.gg or other sites but also because its design is clean and simple with huge amounts of benefitting data.

**Comment by stirante** [comment]
Thank you for suggestion. I'll try to implement this site today.

**Comment by agaertner** [comment]
Thanks. Quick question before you close it. Will you also add summoner spell automation corresponding to the same source of the selected runes?

**Comment by stirante** [comment]
I'm planning to implement items and summoner spells for all sites at a later date. 

Btw for now I'm gonna probably implement this site with the most default items since it has a very unique system of selecting items which adjusts the rest of the build and we don't have yet any way to specify that in an overlay. But still looks very cool and I'll think how we could approach that later.

**Comment by stirante** [comment]
I finally got to finish this. Implemented in https://github.com/stirante/RuneChanger/commit/9baa30a28721b55c85b193c4de0088e9831357c3

Also pushed the changes to the experimental channel. Just check experimental channel in RuneChanger settings and it should ask you to update.
